'use strict';

/**
 * Assembles the installable web build from the shared renderer.
 *
 *   node tools/build-web.js --api=https://pulsedesk-api.<subdomain>.workers.dev
 *
 * The desktop app and the web app run the same index.html, styles.css and app.js;
 * only the bridge underneath them differs (IPC vs fetch).
 */

const fs = require('fs');
const path = require('path');
const { appIcon } = require('../src/services/icon');

const ROOT = path.join(__dirname, '..');
const RENDERER = path.join(ROOT, 'src', 'renderer');
const WEB_SRC = path.join(ROOT, 'web', 'src');
const OUT = path.join(ROOT, 'web', 'dist');

const arg = (name, fallback) => {
  const hit = process.argv.find((a) => a.startsWith(`--${name}=`));
  return hit ? hit.slice(name.length + 3) : fallback;
};

const API = (arg('api', process.env.PULSE_API || '')).replace(/\/+$/, '');

function buildIndex() {
  let html = fs.readFileSync(path.join(RENDERER, 'index.html'), 'utf8');

  const connect = API ? ` ${API}` : '';
  html = html.replace(
    /<meta http-equiv="Content-Security-Policy"[\s\S]*?\/>/,
    `<meta http-equiv="Content-Security-Policy"
        content="default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'${connect}; manifest-src 'self';" />`
  );

  html = html.replace(
    '<link rel="stylesheet" href="styles.css" />',
    `<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
  <meta name="theme-color" content="#05060f" />
  <meta name="description" content="Hyped stocks, portfolio P&amp;L with a printable statement, market news with rise/fall calls, 5-hour crypto pumps and world market clocks. Free, no login." />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
  <meta name="apple-mobile-web-app-title" content="PulseDesk" />
  <link rel="manifest" href="./manifest.webmanifest" />
  <link rel="icon" href="./icon-192.png" />
  <link rel="apple-touch-icon" href="./icon-192.png" />
  <link rel="stylesheet" href="styles.css" />
  <link rel="stylesheet" href="web.css" />`
  );

  // Desktop-only controls in the settings dialog.
  html = html
    .replace('<label>Always on top <input id="sTop" type="checkbox" /></label>', '<label class="desktop-only">Always on top <input id="sTop" type="checkbox" /></label>')
    .replace('<label>All desktops <input id="sAll" type="checkbox" /></label>', '<label class="desktop-only">All desktops <input id="sAll" type="checkbox" /></label>')
    .replace('<label>Opacity <input id="sOpacity" type="range" min="0.4" max="1" step="0.05" /></label>', '<label class="desktop-only">Opacity <input id="sOpacity" type="range" min="0.4" max="1" step="0.05" /></label>');

  html = html.replace(
    'Ctrl+Alt+P hide · Ctrl+Alt+R refresh · drag the title bar to move',
    'free · no login · your holdings stay on this device'
  );

  html = html.replace(
    '<script src="app.js"></script>',
    '<script src="config.js"></script>\n  <script src="web-bridge.js"></script>\n  <script src="app.js"></script>\n  <script src="install.js"></script>'
  );

  html = html.replace(
    '</body>',
    '  <footer style="position:fixed;bottom:0;right:12px;font-size:9px;color:#5d6893;letter-spacing:1px;z-index:1">by Dheerav Tandon</footer>\n</body>'
  );

  fs.writeFileSync(path.join(OUT, 'index.html'), html, 'utf8');
}

function main() {
  fs.rmSync(OUT, { recursive: true, force: true });
  fs.mkdirSync(OUT, { recursive: true });

  buildIndex();
  ['styles.css', 'app.js'].forEach((f) => fs.copyFileSync(path.join(RENDERER, f), path.join(OUT, f)));
  ['web-bridge.js', 'install.js', 'web.css', 'sw.js', 'manifest.webmanifest', 'stats.html'].forEach((f) =>
    fs.copyFileSync(path.join(WEB_SRC, f), path.join(OUT, f))
  );

  fs.writeFileSync(
    path.join(OUT, 'config.js'),
    `// Generated by tools/build-web.js — points the web app at the edge worker.\nwindow.PULSE_API = ${JSON.stringify(API)};\n`,
    'utf8'
  );

  fs.writeFileSync(path.join(OUT, 'icon-192.png'), appIcon(192));
  fs.writeFileSync(path.join(OUT, 'icon-512.png'), appIcon(512));
  fs.writeFileSync(path.join(OUT, 'favicon.png'), appIcon(64));
  // Tells GitHub Pages not to run the output through Jekyll.
  fs.writeFileSync(path.join(OUT, '.nojekyll'), '');

  if (!API) console.warn('! No --api given: the web build will load but fetch nothing until config.js is filled in.');
  console.log(`web build → ${OUT}`);
  console.log(`API base  → ${API || '(unset)'}`);
  console.log('files     →', fs.readdirSync(OUT).join(', '));
}

main();
